dist: bionic

jobs:
  include:
    - os: linux
      language: c
      env:
        - MATRIX_EVAL="CC=gcc" CF=-DBUILD_SHARED_LIBS=OFF
    - os: linux
      language: c
      env:
        - MATRIX_EVAL="CC='gcc -m32'" CF="-DBUILD_SHARED_LIBS=OFF -DCMAKE_LIBRARY_PATH=/usr/lib32"
          PACKAGES="gcc-multilib lib32z1-dev" ARCH="i686"
    - os: linux
      language: c
      env:
        - MATRIX_EVAL="CC=gcc" CF=-DBUILD_SHARED_LIBS=ON

before_install:
  - sudo apt-get install -y rpm
  - git clone https://github.com/huskyproject/huskylib ~/build/huskyproject/huskylib
  - git clone https://github.com/huskyproject/smapi ~/build/huskyproject/smapi
  - git clone https://github.com/huskyproject/fidoconf ~/build/huskyproject/fidoconf
  - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
    --no-upgrade -qq $PACKAGES; fi
  - wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -
  - sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list
  - sudo apt-get update; sudo apt-get install -y pvs-studio

script:
  - echo TRAVIS_BRANCH=$TRAVIS_BRANCH
  - echo TRAVIS_TAG=$TRAVIS_TAG
  - if [[ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" && "$TRAVIS_BRANCH" != "master" ]]; then CURR_BRANCH="$TRAVIS_BRANCH"; fi
  - echo CURR_BRANCH=$CURR_BRANCH
  - eval "${MATRIX_EVAL}"
  - cd  ~/build/huskyproject/huskylib
  - if [[ -n "$CURR_BRANCH" ]]; then git checkout "$CURR_BRANCH"; true; fi
  - git branch
  - mkdir build
  - cd build
  - cmake .. "${CF}"
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/smapi
  - if [[ -n "$CURR_BRANCH" ]]; then git checkout "$CURR_BRANCH"; true; fi
  - git branch
  - mkdir build
  - cd build
  - cmake .. "${CF}"
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/fidoconf
  - if [[ -n "$CURR_BRANCH" ]]; then git checkout "$CURR_BRANCH"; true; fi
  - git branch
  - mkdir build
  - cd build
  - cmake .. "${CF}"
  - cmake --build .
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  - if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer credentials -o $TRAVIS_BUILD_DIR/PVS-Studio.lic $PVS_USERNAME $PVS_KEY; fi
  - if [[ -n "$PVS_USERNAME" ]]; then cmake . -Bbuild "${CF}" -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DCPACK_DEBIAN_PACKAGE_MAINTAINER=travis-ci; fi
  - if [[ -z "$PVS_USERNAME" ]]; then cmake . -Bbuild "${CF}" -DCPACK_DEBIAN_PACKAGE_MAINTAINER=travis-ci; fi
  - if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer trace -- cmake --build build; else cmake --build build; fi
  - if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer analyze -l $TRAVIS_BUILD_DIR/PVS-Studio.lic -s $TRAVIS_BUILD_DIR/suppress_base.json -o build/pvs.log; fi
  - if [[ -n "$PVS_USERNAME" ]]; then plog-converter -a 'GA:1,2;64:1,2;OP:1,2' -t tasklist -o build/pvs.tasks build/pvs.log; fi
  - if [[ -n "$PVS_USERNAME" ]]; then cat build/pvs.tasks; fi
  - if [[ -n "$PVS_USERNAME" ]]; then ! grep -vP '\serr\s+Help:' build/pvs.tasks | grep -P '\serr\s'; fi
  - cd build
  - cpack
