os: linux
dist: xenial
language: c
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
jobs:
  include:
      env:
        - MATRIX_EVAL="CC=gcc" CF=-DBUILD_SHARED_LIBS=OFF
        - MATRIX_EVAL="CC=gcc" CF=-DBUILD_SHARED_LIBS=ON
before_install:
  - sudo apt-get install -y rpm
  - git clone https://github.com/huskyproject/huskylib ~/build/huskyproject/huskylib
  - git clone https://github.com/huskyproject/smapi ~/build/huskyproject/smapi
  - git clone https://github.com/huskyproject/fidoconf ~/build/huskyproject/fidoconf
  - wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -
  - sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list
  - sudo apt-get update; sudo apt-get install -y pvs-studio
script:
  - eval "${MATRIX_EVAL}"
  - cd  ~/build/huskyproject/huskylib
  - mkdir build
  - cd build
  - cmake .. "${CF}"
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/smapi
  - mkdir build
  - cd build
  - cmake .. "${CF}"
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/fidoconf
  - mkdir build
  - cd build
  - cmake .. "${CF}"
  - cmake --build .
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  - if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer credentials -o $TRAVIS_BUILD_DIR/PVS-Studio.lic $PVS_USERNAME $PVS_KEY; fi
  - if [[ -n "$PVS_USERNAME" ]]; then cmake . -Bbuild "${CF}" -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DCPACK_DEBIAN_PACKAGE_MAINTAINER=travis-ci; fi
  - if [[ -z "$PVS_USERNAME" ]]; then cmake . -Bbuild "${CF}" -DCPACK_DEBIAN_PACKAGE_MAINTAINER=travis-ci; fi
  - if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer trace -- cmake --build build; else cmake --build build; fi
  - if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer analyze -l $TRAVIS_BUILD_DIR/PVS-Studio.lic -s $TRAVIS_BUILD_DIR/suppress_base.json -o build/pvs.log; fi
  - if [[ -n "$PVS_USERNAME" ]]; then plog-converter -a 'GA:1,2;64:1,2;OP:1,2' -t tasklist -o build/pvs.tasks build/pvs.log; fi
  - if [[ -n "$PVS_USERNAME" ]]; then cat build/pvs.tasks; fi
  - if [[ -n "$PVS_USERNAME" ]]; then ! grep -vP '\serr\s+Help:' build/pvs.tasks | grep -P '\serr\s'; fi
  - cd build
  - cpack
