language: c

os:
  - linux
  - osx
branches:
  only:
    - master
compiler:
  - gcc
  - clang
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpm; fi
  - git clone https://github.com/huskyproject/huskylib ~/build/huskyproject/huskylib
  - git clone https://github.com/huskyproject/smapi ~/build/huskyproject/smapi
  - git clone https://github.com/huskyproject/fidoconf ~/build/huskyproject/fidoconf
script:
  - cd  ~/build/huskyproject/huskylib
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/smapi
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/fidoconf
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cpack
