language: c

os:
  - linux
  - osx
branches:
  only:
    - master
compiler:
  - gcc
  - clang
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpm; fi
  - git clone https://github.com/askovpen/huskylib ~/build/askovpen/huskylib
  - git clone https://github.com/askovpen/smapi ~/build/askovpen/smapi
  - git clone https://github.com/askovpen/fidoconf ~/build/askovpen/fidoconf
script:
  - cd  ~/build/askovpen/huskylib
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install
  - cd  ~/build/askovpen/smapi
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install
  - cd  ~/build/askovpen/fidoconf
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install
  - cd  ~/build/askovpen/areafix
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cpack
